name: Code Coverage

on:
  pull_request:
    branches:
      - master
      - Wen-MY-patch-1-update-code-coverage
  push:
    branches:
      - master
      - Wen-MY-patch-1-update-code-coverage
permissions: read-all

env:
  MAVEN_OPTS: -Xmx2048m -Xms1024m
  LANG: en_US.utf8

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Code coverage on Java ${{ matrix.java }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
